POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
      "id": "100",
      "firstName": "Jane",
      "lastName": "Smith",
      "phoneNumber": "555678",
      "email": "jane.smith@company.com",
      "country": "Estonia"
}


###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": "200",
  "firstName": "John",
  "lastName": "Smith",
  "phoneNumber": "555789",
  "email": "john.smith@company.com",
  "country": "Germany"
}

###
POST http://127.0.0.1:8080/customer
Content-Type: application/json

{
  "id": "300",
  "firstName": "Mary",
  "lastName": "Smith",
  "phoneNumber": "555437",
  "email": "mary.smith@company.com",
  "country": "Poland"
}


###
GET http://127.0.0.1:8080/customer
Accept: application/json

###
GET http://127.0.0.1:8080/customer/200
Accept: application/json

###
GET http://127.0.0.1:8080/customer/500
Accept: application/json

###
DELETE http://127.0.0.1:8080/customer/100

###
DELETE http://127.0.0.1:8080/customer/500